// spedest code ever....

export async function Arena(accountId: string, hype: number) {
  const ver = Bun.env.SEASON;
  return {
    events: [
      {
        announcementTime: "2024-03-01T21:56:59Z",
        appId: null,
        beginTime: "2024-02-29T21:56:59Z",
        displayDataId: "core_arena_solo",
        endTime: "9999-12-31T23:59:59.000Z",
        environment: null,
        eventGroup: "",
        eventId: `epicgames_Arena_S${ver}_Solo`,
        eventWindows: [
          {
            additionalRequirements: [],
            beginTime: "2024-02-29T21:56:59Z",
            blackoutPeriods: [],
            canLiveSpectate: false,
            countdownBeginTime: "2023-06-15T15:00:00.000Z",
            endTime: "9999-12-31T23:59:59.000Z",
            eventTemplateId: `eventTemplate_Arena_S${ver}_Division1_Solo`,
            eventWindowId: `Arena_S${ver}_Division1_Solo`,
            isTBD: false,
            metadata: {
              RoundType: "Arena",
              ThresholdToAdvanceDivision: 400,
              divisionRank: 0,
            },
            payoutDelay: 1,
            requireAllTokens: [`ARENA_S${ver}_Division1`],
            requireAllTokensCaller: [],
            requireAnyTokens: [],
            requireAnyTokensCaller: [],
            requireNoneTokensCaller: [
              `ARENA_S${ver}_Division2`,
              `ARENA_S${ver}_Division3`,
              `ARENA_S${ver}_Division4`,
              `ARENA_S${ver}_Division5`,
              `ARENA_S${ver}_Division6`,
              `ARENA_S${ver}_Division7`,
              `ARENA_S${ver}_Division8`,
              `ARENA_S${ver}_Division9`,
              `ARENA_S${ver}_Division10`,
            ],
            round: 0,
            scoreLocations: [],
            teammateEligibility: "any",
            visibility: "public",
          },
          {
            additionalRequirements: [],
            beginTime: "2024-02-29T21:56:59Z",
            blackoutPeriods: [],
            canLiveSpectate: false,
            countdownBeginTime: "2023-06-15T15:00:00.000Z",
            endTime: "9999-12-31T23:59:59.000Z",
            eventTemplateId: `eventTemplate_Arena_S${ver}_Division2_Solo`,
            eventWindowId: `Arena_S${ver}_Division2_Solo`,
            isTBD: false,
            metadata: {
              RoundType: "Arena",
              ThresholdToAdvanceDivision: 800,
              divisionRank: 1,
            },
            payoutDelay: 1,
            requireAllTokens: [`ARENA_S${ver}_Division2`],
            requireAllTokensCaller: [],
            requireAnyTokens: [],
            requireAnyTokensCaller: [],
            requireNoneTokensCaller: [
              `ARENA_S${ver}_Division1`,
              `ARENA_S${ver}_Division3`,
              `ARENA_S${ver}_Division4`,
              `ARENA_S${ver}_Division5`,
              `ARENA_S${ver}_Division6`,
              `ARENA_S${ver}_Division7`,
              `ARENA_S${ver}_Division8`,
              `ARENA_S${ver}_Division9`,
              `ARENA_S${ver}_Division10`,
            ],
            round: 1,
            scoreLocations: [],
            teammateEligibility: "any",
            visibility: "public",
          },
          {
            additionalRequirements: [],
            beginTime: "2024-02-29T21:56:59Z",
            blackoutPeriods: [],
            canLiveSpectate: false,
            countdownBeginTime: "2023-06-15T15:00:00.000Z",
            endTime: "9999-12-31T23:59:59.000Z",
            eventTemplateId: `eventTemplate_Arena_S${ver}_Division3_Solo`,
            eventWindowId: `Arena_S${ver}_Division3_Solo`,
            isTBD: false,
            metadata: {
              RoundType: "Arena",
              ThresholdToAdvanceDivision: 1500,
              divisionRank: 2,
            },
            payoutDelay: 1,
            requireAllTokens: [`ARENA_S${ver}_Division3`],
            requireAllTokensCaller: [],
            requireAnyTokens: [],
            requireAnyTokensCaller: [],
            requireNoneTokensCaller: [
              `ARENA_S${ver}_Division1`,
              `ARENA_S${ver}_Division2`,
              `ARENA_S${ver}_Division4`,
              `ARENA_S${ver}_Division5`,
              `ARENA_S${ver}_Division6`,
              `ARENA_S${ver}_Division7`,
              `ARENA_S${ver}_Division8`,
              `ARENA_S${ver}_Division9`,
              `ARENA_S${ver}_Division10`,
            ],
            round: 2,
            scoreLocations: [],
            teammateEligibility: "any",
            visibility: "public",
          },
          {
            additionalRequirements: [],
            beginTime: "2024-02-29T21:56:59Z",
            blackoutPeriods: [],
            canLiveSpectate: false,
            countdownBeginTime: "2023-06-15T15:00:00.000Z",
            endTime: "9999-12-31T23:59:59.000Z",
            eventTemplateId: `eventTemplate_Arena_S${ver}_Division4_Solo`,
            eventWindowId: `Arena_S${ver}_Division4_Solo`,
            isTBD: false,
            metadata: {
              RoundType: "Arena",
              ThresholdToAdvanceDivision: 2000,
              divisionRank: 3,
            },
            payoutDelay: 1,
            requireAllTokens: [`ARENA_S${ver}_Division4`],
            requireAllTokensCaller: [],
            requireAnyTokens: [],
            requireAnyTokensCaller: [],
            requireNoneTokensCaller: [
              `ARENA_S${ver}_Division1`,
              `ARENA_S${ver}_Division2`,
              `ARENA_S${ver}_Division3`,
              `ARENA_S${ver}_Division5`,
              `ARENA_S${ver}_Division6`,
              `ARENA_S${ver}_Division7`,
              `ARENA_S${ver}_Division8`,
              `ARENA_S${ver}_Division9`,
              `ARENA_S${ver}_Division10`,
            ],
            round: 3,
            scoreLocations: [],
            teammateEligibility: "any",
            visibility: "public",
          },
          {
            additionalRequirements: [],
            beginTime: "2024-02-29T21:56:59Z",
            blackoutPeriods: [],
            canLiveSpectate: false,
            countdownBeginTime: "2023-06-15T15:00:00.000Z",
            endTime: "9999-12-31T23:59:59.000Z",
            eventTemplateId: `eventTemplate_Arena_S${ver}_Division5_Solo`,
            eventWindowId: `Arena_S${ver}_Division5_Solo`,
            isTBD: false,
            metadata: {
              RoundType: "Arena",
              ThresholdToAdvanceDivision: 3500,
              divisionRank: 4,
            },
            payoutDelay: 1,
            requireAllTokens: [`ARENA_S${ver}_Division5`],
            requireAllTokensCaller: [],
            requireAnyTokens: [],
            requireAnyTokensCaller: [],
            requireNoneTokensCaller: [
              `ARENA_S${ver}_Division1`,
              `ARENA_S${ver}_Division2`,
              `ARENA_S${ver}_Division3`,
              `ARENA_S${ver}_Division4`,
              `ARENA_S${ver}_Division6`,
              `ARENA_S${ver}_Division7`,
              `ARENA_S${ver}_Division8`,
              `ARENA_S${ver}_Division9`,
              `ARENA_S${ver}_Division10`,
            ],
            round: 4,
            scoreLocations: [],
            teammateEligibility: "any",
            visibility: "public",
          },
          {
            additionalRequirements: [],
            beginTime: "2024-02-29T21:56:59Z",
            blackoutPeriods: [],
            canLiveSpectate: false,
            countdownBeginTime: "2023-06-15T15:00:00.000Z",
            endTime: "9999-12-31T23:59:59.000Z",
            eventTemplateId: `eventTemplate_Arena_S${ver}_Division6_Solo`,
            eventWindowId: `Arena_S${ver}_Division6_Solo`,
            isTBD: false,
            metadata: {
              RoundType: "Arena",
              ThresholdToAdvanceDivision: 4500,
              divisionRank: 5,
            },
            payoutDelay: 1,
            requireAllTokens: [`ARENA_S${ver}_Division6`],
            requireAllTokensCaller: [],
            requireAnyTokens: [],
            requireAnyTokensCaller: [],
            requireNoneTokensCaller: [
              `ARENA_S${ver}_Division1`,
              `ARENA_S${ver}_Division2`,
              `ARENA_S${ver}_Division3`,
              `ARENA_S${ver}_Division4`,
              `ARENA_S${ver}_Division5`,
              `ARENA_S${ver}_Division7`,
              `ARENA_S${ver}_Division8`,
              `ARENA_S${ver}_Division9`,
              `ARENA_S${ver}_Division10`,
            ],
            round: 5,
            scoreLocations: [],
            teammateEligibility: "any",
            visibility: "public",
          },
          {
            additionalRequirements: [],
            beginTime: "2024-02-29T21:56:59Z",
            blackoutPeriods: [],
            canLiveSpectate: false,
            countdownBeginTime: "2023-06-15T15:00:00.000Z",
            endTime: "9999-12-31T23:59:59.000Z",
            eventTemplateId: `eventTemplate_Arena_S${ver}_Division7_Solo`,
            eventWindowId: `Arena_S${ver}_Division7_Solo`,
            isTBD: true,
            metadata: {
              RoundType: "Arena",
              ThresholdToAdvanceDivision: 7500,
              divisionRank: 6,
            },
            payoutDelay: 30,
            requireAllTokens: [`ARENA_S${ver}_Division7`],
            requireAllTokensCaller: [],
            requireAnyTokens: [],
            requireAnyTokensCaller: [],
            requireNoneTokensCaller: [
              `ARENA_S${ver}_Division1`,
              `ARENA_S${ver}_Division2`,
              `ARENA_S${ver}_Division3`,
              `ARENA_S${ver}_Division4`,
              `ARENA_S${ver}_Division5`,
              `ARENA_S${ver}_Division6`,
              `ARENA_S${ver}_Division8`,
              `ARENA_S${ver}_Division9`,
              `ARENA_S${ver}_Division10`,
            ],
            round: 6,
            scoreLocations: [],
            teammateEligibility: "any",
            visibility: "public",
          },
        ],
        gameId: "Fortnite",
        link: null,
        metadata: {
          TrackedStats: [
            "PLACEMENT_STAT_INDEX",
            "TEAM_ELIMS_STAT_INDEX",
            "MATCH_PLAYED_STAT",
          ],
          minimumAccountLevel: 25,
        },
        platformMappings: {},
        platforms: ["PS4", "XboxOne", "Switch", "Android", "IOS", "Windows"],
        regionMappings: {},
        regions: ["NAE", "ME", "NAW", "OCE", "ASIA", "EU", "BR"],
      },
    ],
    player: {
      accountId: accountId,
      gameId: "Fortnite",
      groupIdentity: {},
      pendingPayouts: [],
      pendingPenalties: {},
      persistentScores: { Hype: hype },
      teams: {},
      tokens: [`ARENA_S${ver}_Division1`],
    },
    templates: [
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division1_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: 0,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division2_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: 0,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division3_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: -10,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division4_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: -20,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division5_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: -40,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division6_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: -40,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division7_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: -50,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division8_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: -60,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division9_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: -70,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
      {
        eventTemplateId: `eventTemplate_Arena_S${ver}_Division10_Solo`,
        gameId: "Fortnite",
        matchcAP: 0,
        persistentScoreId: "Hype",
        playlistId: "Playlist_ShowdownAlt_Solo",
        scoringRules: [
          {
            matchRule: "gtw",
            rewardTiers: [
              {
                keyValue: 1,
                multiplicative: false,
                pointsEarned: -80,
              },
            ],
            trackedStat: "MATCH_PLAYED_STAT",
          },
          {
            matchRule: "lte",
            rewardTiers: [
              { keyValue: 1, multiplicative: false, pointsEarned: 25 },
              { keyValue: 5, multiplicative: false, pointsEarned: 15 },
              { keyValue: 15, multiplicative: false, pointsEarned: 10 },
              { keyValue: 25, multiplicative: false, pointsEarned: 5 },
            ],
            trackedStat: "PLACEMENT_STAT_INDEX",
          },
          {
            matchRule: "gte",
            rewardTiers: [
              { keyValue: 1, multiplicative: true, pointsEarned: 20 },
            ],
            trackedStat: "TEAM_ELIMS_STAT_INDEX",
          },
        ],
      },
    ],
  };
}
